# Generated by Django 4.1.6 on 2023-02-09 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DecryptedText",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("inputText", models.CharField(max_length=1000)),
                ("inputWord", models.CharField(max_length=50)),
                ("outputText", models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name="EncryptedText",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("inputText", models.CharField(max_length=1000)),
                ("inputWord", models.CharField(max_length=50)),
                ("outputText", models.CharField(max_length=1000)),
            ],
        ),
    ]
