# Generated by Django 4.1.6 on 2023-02-09 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Encryption", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="decryptedtext",
            old_name="outputText",
            new_name="decrypted",
        ),
        migrations.RenameField(
            model_name="decryptedtext",
            old_name="inputWord",
            new_name="word",
        ),
        migrations.RenameField(
            model_name="encryptedtext",
            old_name="outputText",
            new_name="encrypted",
        ),
        migrations.RenameField(
            model_name="encryptedtext",
            old_name="inputWord",
            new_name="word",
        ),
    ]
