# Generated by Django 4.1.6 on 2023-02-10 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Encryption", "0002_rename_outputtext_decryptedtext_decrypted_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="decryptedtext",
            name="decrypted",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="decryptedtext",
            name="inputText",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="encryptedtext",
            name="encrypted",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="encryptedtext",
            name="inputText",
            field=models.TextField(),
        ),
    ]
