# Generated by Django 4.1.6 on 2023-02-10 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Encryption", "0003_alter_decryptedtext_decrypted_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DecryptedText",
        ),
        migrations.DeleteModel(
            name="EncryptedText",
        ),
    ]
